version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: log-symbols
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: inquirer
    versions:
    - 7.3.3
    - 8.0.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: inquirer-datepicker
    versions:
    - 2.0.0
  - dependency-name: chalk
    versions:
    - 4.1.0
